[colors]
ansi = [
    "#000000",
    "#eecc6c",
    "#f3ecd4",
    "#b80d0d",
    "#707880",
    "#999999",
    "#aaaaaa",
    "#c1c1c1",
]
background = "#000000"
brights = [
    "#333333",
    "#eecc6c",
    "#f3ecd4",
    "#b80d0d",
    "#707880",
    "#999999",
    "#aaaaaa",
    "#c1c1c1",
]
cursor_bg = "#f6e954"
cursor_border = "#f6e954"
foreground = "#c3ccd5"
selection_bg = "#c3ccd5"
# cursor_border = "#c1c1c1"
# cursor_bg = "#c1c1c1"
# foreground = "#c1c1c1"
# selection_bg = "#c1c1c1"
cursor_fg = "#000000"
selection_fg = "#000000"

[colors.indexed]
16 = "#aaaaaa"
17 = "#444444"
18 = "#121212"
19 = "#222222"
20 = "#999999"
21 = "#999999"

[metadata]
aliases = []
author = "shalst: stolen from - metalelf0 (https://github.com/metalelf0)"
name = "Black Noodle"
